---
- hosts: all

  # gather_facts: no
  # pre_tasks:
  #   - name: 'install python2'
  #     raw: sudo apt-get -y install python

  vars_files:
    - vars.yml

  roles:
    - swap
    - ntp
    - git
    - clamav
    - mysql
    - php
    - php-mysql
    - composer
    - apache
    - apache-php-fpm
    - htpasswd
    - certbot
    - java
    - solr
    - munin-node
    - munin
    - firewall
