- src: geerlingguy.swap
  name: swap
- src: geerlingguy.ntp
  name: ntp
- src: geerlingguy.postfix
  name: postfix
- src: geerlingguy.mysql
  name: mysql
- src: geerlingguy.php
  name: php
- src: geerlingguy.php-mysql
  name: php-mysql
- src: geerlingguy.apache
  name: apache
- src: geerlingguy.htpasswd
  name: htpasswd
- src: geerlingguy.apache-php-fpm
  name: apache-php-fpm
- src: geerlingguy.pimpmylog
  name: pimpmylog
- src: geerlingguy.certbot
  name: certbot
- src: geerlingguy.clamav
  name: clamav
- src: geerlingguy.git
  name: git
- src: geerlingguy.composer
  name: composer
- src: geerlingguy.java
  name: java
- src: geerlingguy.solr
  name: solr
- src: geerlingguy.firewall
  name: firewall
- src: geerlingguy.munin
  name: munin
- src: geerlingguy.munin-node
  name: munin-node
- src: geerlingguy.security
  name: security
