---
services: docker

env:
  - distro: centos7
    playbook: test-apache.yml
  - distro: ubuntu1604
    playbook: test-nginx.yml
  - distro: debian9
    playbook: test-nginx.yml

addons:
  hosts:
    - htpassword.test

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure http basic auth is required to connect to the vhost.
  - 'docker exec --tty ${container_id} env TERM=xterm bash -c "curl --write-out %{http_code} --silent --output /dev/null http://localhost/ | grep 401"'
  - 'docker exec --tty ${container_id} env TERM=xterm curl -u johndoe:supersecure http://localhost/'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
